name: All Specs
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  # TODO: Environment variables?
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |-
            node_modules
            vendor/bundle
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12.13.1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: gem install bundler:2.1.4
      - run: npm install -g yarn@1.22.4
      - run: bundle install
      - run: yarn install
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:test:prepare
      - name: Run Rspec
        run: bundle exec rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Run Cucumber
        run: bundle exec cucumber
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/.resultset.json
          fail_ci_if_error: false
          verbose: true